spring.application.name=api-adocao-animais

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/adocao_animais
spring.datasource.username=postgres
spring.datasource.password=Bronte96*

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
